config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events do
  	resources :comments, :controller => 'event_comments'
  end
  root :to => 'events#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :events
end

app/models/comment.rb
class Comment < ApplicationRecord
	# 欄位名稱可以用簡單點 因為一般程式碼會變成 @comment.comment_text
	# 可能都不如@comment.content之類來得好

	# 缺少驗證
	validates_presence_of :comment_text
	belongs_to :event
	belongs_to :user
end

app/models/event.rb
class Event < ApplicationRecord
	validates_presence_of :title
	belongs_to :user
	belongs_to :category
	has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # what's this?
  # has_many :questions , ->{ where(["created_at > ?", Time.now - 7.day]).order("id DESC") },  :dependent => :destroy
  # has_many :comments , ->{ where(["created_at > ?", Time.now - 7.day]).order("id DESC") }, :dependent => :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :events
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/event_comments_controller.rb
class EventCommentsController < ApplicationController
  before_action :find_event
  before_action :set_own_comment, :only => [:destroy, :edit, :update]

  def index
    @comments = @event.comments
  end

  def show
    @comment = @event.comments.find(params[:id])
  end

  def new
    @comment = @event.comments.build
  end

  def create
    @comment = @event.comments.build(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = "comment was successfully created"
      redirect_to event_url(@event)
    else
      render "events/show"
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      flash[:notice] = "comment was successfully updated"
      redirect_to event_url(@event)
    else
      render :action => :edit
    end
  end

  def destroy
    @comment.destroy
    flash[:alert] = "comment was successfully deleted"
    redirect_to event_url(@event)
  end

  protected

  def find_event
    @event = Event.find(params[:event_id])
  end

  def comment_params
    params.require(:comment).permit(:comment_text)
  end

  def set_own_comment
    @comment = current_user.comments.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!
	# set event 單數
	before_action :set_event, :only =>[:show]
	before_action :event_value, :only => [:index]
	before_action :set_own_event, :only => [:update , :edit , :destroy]
	def index
		@events = Event.includes(:comments , :user, :category).page(params[:page]).per(5)
		# 這一行在view裡面完全沒用到
		# @categories = Category.all
	end

	def new
		@event = Event.new
	end

	def create
		@event = Event.new(event_params)
		@events =Event.includes(:comments , :user, :category).page(params[:page]).per(5)
		@event.user = current_user
		if @event.save
			flash[:notice] = "災情信息成功發布"
			redirect_to events_url
		else
			# 這一行在view裡面完全沒用到
		 # @categories = Category.all
			render :action => :index	
		end	
	end

	def show
		@page_title = @event.title
		@comments = @event.comments
		if params[:edit_comment]
			# 缺少後端驗證
			@comment = current_user.comments.find([params[:edit_comment]])
		else
			@comment = Comment.new
		end	
	end
	
	def edit		
	end

	def update
		if @event.update(event_params)
			flash[:notice] = "災情信息發布成功"
			redirect_to event_url(@event)
		else 
			render :edit 
		end		
	end	

	def destroy
		@event.destroy
		flash[:alert] = "災情信息已經刪除"
		redirect_to events_url
	end 

	private
	
	def event_params
		params.require( :event ).permit( :title, :description, :category_id,  :category_ids => [] )
	end	 	

	def set_event
		@event = Event.find(params[:id])
	end
		
	def event_value
		unless @event 
			@event = Event.new
		end	 	
	end

	def set_own_event
		# 確保event的使用者是current_user
		@event = current_user.events.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_comments_helper.rb
module EventCommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/event_comments/edit.html.erb
<%= form_for @comment, :url => event_comment_path(@event, @comment), :html => { :method => :patch } do |f| %>
   <%= f.text_field :comment_text %>
   <%= f.submit %>
<% end %>

app/views/event_comments/index.html.erb
<ul>
  <% @comments.each do |comment| %>
      <li>
        <%= comment.comment_text %>
        <%= link_to 'show', event_comment_path(@event, comment) %>
        <%= link_to 'edit', edit_event_comment_path(@event, comment) %>
        <%= link_to 'destroy', event_comment_path(@event, comment),
                    :method => :delete %>
      </li>
  <% end %>
</ul>
<%= link_to 'new answer', new_event_comment_path(@event) %>

app/views/event_comments/new.html.erb
<%= form_for @comment, :url => event_comments_path(@event) do |f| %>
   <%= f.text_field :comment_text %>
   <%= f.submit %>
<% end %>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
    <ul>
      <% @event.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<div class="form-group">
  <%= f.label :title, "信息標題" %>
</div>
<div>
  <%= f.text_field :title, :class => "form-control" %>
</div>
<div>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
</div>
<div class="form-group">
  <%= f.label :description %>
  <%= f.text_field :description, :placeholder => "災情信息內容", :class => "form-control" %>
</div>
	

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method => :patch  do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<%= f.submit "Update" , :class => "btn btn-primary" %>
<% end %>

app/views/events/index.html.erb
<h1>地震災情支援網</h1>

<table class="table">
  <tr class="sort">
    <th>災情情況發布</th>
    <th>Category</th>
    <th>Last Reply</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <% @events.each do |event| %>

      <tr>
        <td width=60%>
          <%= link_to event.title, event_path(event) %>
        </td>
        <td width=10%>
          <p><%= event.category.try(:name) %></p>
        </td>
        <td width=10%>
          <%= event.comments.last.try(:updated_at) %>
        </td>
        <% if current_user == event.user %>
            <td width=10%>
              <%= link_to 'Edit', edit_event_path(event), :class => "btn btn-primary" %>
            </td>
            <td width=10%>
              <%= button_to 'Delete', event_path(event), :method => :delete, :data => { :confirm => "確定要刪除此災情信息嗎？ " }, :class => "btn btn-danger" %>
            </td>
        <% else %>
            <td></td>
            <td></td>
        <% end %>
      </tr>
  <% end %>
</table>

<%= paginate @events %>

<h3>請在此發布新的災情信息或求救: </h3>
<%= form_for @event, :url => events_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    <%= f.submit "現在就發布信息", :class => "btn btn-default" %>
<% end %>	

app/views/events/show.html.erb
<h2><%= @event.title %></h2>

<table class="table">
  <tr>
    <td>
      <p>Category: <%= @event.category.try(:name) %></p>
    </td>
    <td>
      <p><%= simple_format(@event.description) %></p>
    </td>
    <% if current_user == @event.user %>
        <td>
          <%= link_to 'Edit', edit_event_path(@event), :class => "btn btn-primary" %>
        </td>
        <td>
          <%= link_to 'Delete', event_path(@event), :method => :delete, :data => { :confirm => "確定要刪除此災情信息嗎？ " }, :class => "btn btn-danger" %>
        </td>
    <% else %>
        <td></td>
        <td></td>
    <% end %>
  </tr>
  <tr>
  </tr>
</table>

<ul>
  <% @comments.each do |comment| %>
      <li>
        <%= comment.comment_text %>
        <% if current_user == comment.user %>
            <%= link_to 'edit', edit_event_comment_path(@event, comment) %>
            <%= link_to 'delete', event_comment_path(@event, comment), :method => :delete %>
        <% end %>
      </li>
  <% end %>
  <%= form_for [@event, @comment] do |f| %>
      <%= f.text_field :comment_text %>
      <%= f.submit %>
  <% end %>
</ul>

<p><%= link_to 'Back to Index', events_path, :class => "btn btn-default" %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Earthquake</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <% if current_user %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
  <% end %>
    <p class="notice"><%= notice %></p>
 	<p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>